// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: currency_converter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertCurrencyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InitialCurrency string                 `protobuf:"bytes,1,opt,name=initial_currency,json=initialCurrency,proto3" json:"initial_currency,omitempty"`
	InitialAmount   float64                `protobuf:"fixed64,2,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	TargetCurrency  string                 `protobuf:"bytes,3,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertCurrencyRequest) Reset() {
	*x = ConvertCurrencyRequest{}
	mi := &file_currency_converter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertCurrencyRequest) ProtoMessage() {}

func (x *ConvertCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_converter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertCurrencyRequest.ProtoReflect.Descriptor instead.
func (*ConvertCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_currency_converter_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertCurrencyRequest) GetInitialCurrency() string {
	if x != nil {
		return x.InitialCurrency
	}
	return ""
}

func (x *ConvertCurrencyRequest) GetInitialAmount() float64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *ConvertCurrencyRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

type ConvertCurrencyReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConvertedAmount float64                `protobuf:"fixed64,1,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	TargetCurrency  string                 `protobuf:"bytes,2,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertCurrencyReply) Reset() {
	*x = ConvertCurrencyReply{}
	mi := &file_currency_converter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertCurrencyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertCurrencyReply) ProtoMessage() {}

func (x *ConvertCurrencyReply) ProtoReflect() protoreflect.Message {
	mi := &file_currency_converter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertCurrencyReply.ProtoReflect.Descriptor instead.
func (*ConvertCurrencyReply) Descriptor() ([]byte, []int) {
	return file_currency_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertCurrencyReply) GetConvertedAmount() float64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertCurrencyReply) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

var File_currency_converter_proto protoreflect.FileDescriptor

const file_currency_converter_proto_rawDesc = "" +
	"\n" +
	"\x18currency_converter.proto\x12\x12currency_converter\"\x93\x01\n" +
	"\x16ConvertCurrencyRequest\x12)\n" +
	"\x10initial_currency\x18\x01 \x01(\tR\x0finitialCurrency\x12%\n" +
	"\x0einitial_amount\x18\x02 \x01(\x01R\rinitialAmount\x12'\n" +
	"\x0ftarget_currency\x18\x03 \x01(\tR\x0etargetCurrency\"j\n" +
	"\x14ConvertCurrencyReply\x12)\n" +
	"\x10converted_amount\x18\x01 \x01(\x01R\x0fconvertedAmount\x12'\n" +
	"\x0ftarget_currency\x18\x02 \x01(\tR\x0etargetCurrency2\x85\x01\n" +
	"\x18CurrencyConverterService\x12i\n" +
	"\x0fConvertCurrency\x12*.currency_converter.ConvertCurrencyRequest\x1a(.currency_converter.ConvertCurrencyReply\"\x00B\x18Z\x16my-project/proto;protob\x06proto3"

var (
	file_currency_converter_proto_rawDescOnce sync.Once
	file_currency_converter_proto_rawDescData []byte
)

func file_currency_converter_proto_rawDescGZIP() []byte {
	file_currency_converter_proto_rawDescOnce.Do(func() {
		file_currency_converter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_converter_proto_rawDesc), len(file_currency_converter_proto_rawDesc)))
	})
	return file_currency_converter_proto_rawDescData
}

var file_currency_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_currency_converter_proto_goTypes = []any{
	(*ConvertCurrencyRequest)(nil), // 0: currency_converter.ConvertCurrencyRequest
	(*ConvertCurrencyReply)(nil),   // 1: currency_converter.ConvertCurrencyReply
}
var file_currency_converter_proto_depIdxs = []int32{
	0, // 0: currency_converter.CurrencyConverterService.ConvertCurrency:input_type -> currency_converter.ConvertCurrencyRequest
	1, // 1: currency_converter.CurrencyConverterService.ConvertCurrency:output_type -> currency_converter.ConvertCurrencyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_currency_converter_proto_init() }
func file_currency_converter_proto_init() {
	if File_currency_converter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_converter_proto_rawDesc), len(file_currency_converter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_converter_proto_goTypes,
		DependencyIndexes: file_currency_converter_proto_depIdxs,
		MessageInfos:      file_currency_converter_proto_msgTypes,
	}.Build()
	File_currency_converter_proto = out.File
	file_currency_converter_proto_goTypes = nil
	file_currency_converter_proto_depIdxs = nil
}
