// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: currency_converter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyConverterService_ConvertCurrency_FullMethodName = "/currency_converter.CurrencyConverterService/ConvertCurrency"
)

// CurrencyConverterServiceClient is the client API for CurrencyConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyConverterServiceClient interface {
	ConvertCurrency(ctx context.Context, in *ConvertCurrencyRequest, opts ...grpc.CallOption) (*ConvertCurrencyReply, error)
}

type currencyConverterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyConverterServiceClient(cc grpc.ClientConnInterface) CurrencyConverterServiceClient {
	return &currencyConverterServiceClient{cc}
}

func (c *currencyConverterServiceClient) ConvertCurrency(ctx context.Context, in *ConvertCurrencyRequest, opts ...grpc.CallOption) (*ConvertCurrencyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertCurrencyReply)
	err := c.cc.Invoke(ctx, CurrencyConverterService_ConvertCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyConverterServiceServer is the server API for CurrencyConverterService service.
// All implementations must embed UnimplementedCurrencyConverterServiceServer
// for forward compatibility.
type CurrencyConverterServiceServer interface {
	ConvertCurrency(context.Context, *ConvertCurrencyRequest) (*ConvertCurrencyReply, error)
	mustEmbedUnimplementedCurrencyConverterServiceServer()
}

// UnimplementedCurrencyConverterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyConverterServiceServer struct{}

func (UnimplementedCurrencyConverterServiceServer) ConvertCurrency(context.Context, *ConvertCurrencyRequest) (*ConvertCurrencyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertCurrency not implemented")
}
func (UnimplementedCurrencyConverterServiceServer) mustEmbedUnimplementedCurrencyConverterServiceServer() {
}
func (UnimplementedCurrencyConverterServiceServer) testEmbeddedByValue() {}

// UnsafeCurrencyConverterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyConverterServiceServer will
// result in compilation errors.
type UnsafeCurrencyConverterServiceServer interface {
	mustEmbedUnimplementedCurrencyConverterServiceServer()
}

func RegisterCurrencyConverterServiceServer(s grpc.ServiceRegistrar, srv CurrencyConverterServiceServer) {
	// If the following call panics, it indicates UnimplementedCurrencyConverterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyConverterService_ServiceDesc, srv)
}

func _CurrencyConverterService_ConvertCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServiceServer).ConvertCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyConverterService_ConvertCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServiceServer).ConvertCurrency(ctx, req.(*ConvertCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyConverterService_ServiceDesc is the grpc.ServiceDesc for CurrencyConverterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyConverterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currency_converter.CurrencyConverterService",
	HandlerType: (*CurrencyConverterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertCurrency",
			Handler:    _CurrencyConverterService_ConvertCurrency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency_converter.proto",
}
